site_name: Overlay Image Title
repo_url: https://github.com/rnwolf/overlay_image_title
site_dir: public

markdown_extensions:
  - plantuml_markdown
  - toc:
      anchorlink: True
      separator: "_"
  - admonition
  - tables
  - sane_lists
